[nfs]
172.31.10.169 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/.ssh/id_rsa

[webservers]
172.31.7.153 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/.ssh/id_rsa
172.31.7.164 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/.ssh/id_rsa

[db]
172.31.31.21 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=~/.ssh/id_rsa

[lb]
172.31.6.224 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=~/.ssh/id_rsa
