---
- name: Enable required Apache2 Modules
  become: yes
  shell: |
    a2enmod rewrite
    a2enmod proxy
    a2enmod proxy_balancer
    a2enmod proxy_http
    a2enmod headers
    a2enmod lbmethod_bytraffic
  notify: restart apache2