pipeline {
  agent any
  stages {
    stage('Clone repo') {
      steps {
        git(branch: 'dev', url: 'https://github.com/Anefu/ansible-config-mgt.git')
      }
    }

    stage('Run playbook') {
      steps {
        ansiblePlaybook(credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml')
      }
    }

    stage('Clean up') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }

  }
  post {
    always {
      deleteDir()
    }

  }
}