pipeline {
  agent any
  parameters {
    string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    string(name: 'tag', defaultValue: 'all',  description: 'Tags to run ansible playbook against')
  }
  environment {
    branch = 'feature/jenkinspipeline-stages'
  }
  stages {

    stage('Clean up') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }

    stage('Clone repo') {
      steps {
        git(branch: branch, url: 'https://github.com/Anefu/ansible-config-mgt.git')
      }
    }

    stage('Update ansible.cfg') {
      steps {
        sh "sudo sed -i -e 's/roles_path = \/etc\/ansible\/ansible\.cfg/ roles_path = ${WORKSPACE}/roles' deploy/ansible.cfg"
        sh "export ANSIBLE_CONFIG=${WORKSPACE}/deploy/ansible.cfg"
      }
    }

    stage('Run playbook') {
      steps {
        ansiblePlaybook(credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml', tags: '${tag}')
      }
    }

  }
}
