pipeline {
  agent any
  environment {
        current_env = sh('printenv | grep current_env | cut -d= -f2')
        roles_path    = 'ansible-config-mgt_'+'current_env'
    }
  stages {
    stage('Clone repo') {
      parallel {
        stage('Clone repo') {
          steps {
            git(branch: current_dev, url: 'https://github.com/Anefu/ansible-config-mgt.git')
          }
        }

        stage('Update ansible.cfg') {
          steps {
            sh(script: '/home/script.sh')
          }
        }
      }
    }
    

    stage('Run playbook') {
      steps {
        ansiblePlaybook(credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml')
      }
    }

    stage('Clean up') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }

  }
}
