---
# tasks file for webserver
- name: Install Apache and Git
  become: yes
  yum:
    name:
      - httpd
      - git
      - php
      - php-fpm
      - php-mysqlnd
    state: present

- name: Clone tooling app 
  become: yes
  git:
    repo: "https://github.com/Anefu/tooling.git"
    dest: ~/app
    version: "HEAD"

- name: Copy app to /var/www/html
  become: yes
  copy:
    src: ~/app/html
    dest: /var/www
    remote_src: yes
    mode: "777"
    owner: apache

- name: Make sure httpd service is running
  become: yes
  service:
    name: httpd
    state: started

- name: Set SELinux persistent booleans
  become: yes
  shell: |
    sudo setsebool httpd_can_network_connect 1
    sudo setsebool httpd_can_network_connect_db 1
    sudo setsebool httpd_execmem 1
