---
- import_playbook: ../static-assignments/webservers.yml
- import_playbook: ../static-assignments/mysql.yml

- hosts: nginx
  tasks:
    - name: Load dynamic vars
      include_tasks: ../dynamic-assignments/env-vars.yml

- import_playbook: ../static-assignments/loadbalancers.yml