---
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/mysql.yml

- name: nginx assignment
  ansible.builtin.import_playbook: ../static-assignments/loadbalancers.yml

- name: webservers assignment
  ansible.builtin.import_playbook: ../static-assignments/webservers.yml

- name: artifactory assignment
  ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

# - hosts: sonar
# - name: sonar assignment
#   ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml